### ISSUE TITLE
OpenSSL download broken in docker build

### ISSUE THREAD

**Issue by njsmith** [manylinux/manylinux#15]
wget and I both seem to be getting a 404 here: http://www.openssl.org/source/openssl-1.0.2e.tar.gz

(Also, should probably use https I guess, even if we are checking the sha256 -- belt *and* suspenders.)

**Comment by rmcgibbo** [comment]
looks like the website updated to `f`. maybe that's there way of telling people to update.

**Comment by mpharrigan** [comment]
http://arstechnica.com/security/2016/01/high-severity-bug-in-openssl-allows-attackers-to-decrypt-https-traffic/

**Comment by njsmith** [comment]
How helpful, and yet annoying.
